version: "3.8"

services:

  camtester-nats:
    image: library/nats-streaming:latest
    container_name: camtester-nats
    command: ["--cluster_id", "camtester"]
    ports:
      - 127.0.0.1:8222:8222
    restart: unless-stopped

  camtester-redis-cluster:
    image: grokzen/redis-cluster:latest
    container_name: camtester-redis-cluster
    environment:
      STANDALONE: "false"
      SENTINEL: "false"
    restart: unless-stopped

  camtester-pinger:
    image: camtester-pinger
    container_name: camtester-pinger
    build: ./camtester-pinger
    environment:
      NATS_URL: "nats://camtester-nats:4222"
      NATS_CLUSTER_ID: "camtester"
      NATS_CLIENT_ID: "camtester-pinger"
      GEO_LOCATION: "moscow"
      CONCURRENCY: "100"
    sysctls:
      net.ipv4.ping_group_range: "0   2147483647"
    depends_on:
      - camtester-nats
    stop_grace_period: 11s
    restart: unless-stopped

  restreamer:
    image: restreamer
    container_name: restreamer
    build: ./restreamer
    restart: unless-stopped

  restreamer-provider:
    image: restreamer-provider
    container_name: restreamer-provider
    build: ./restreamer-provider
    environment:
      STORAGE_FILE: "/var/lib/restreamer-provider/storage.json"
    volumes:
      - "restreamer-provider:/var/lib/restreamer-provider"
    ports:
      - 127.0.0.1:3000:80
    restart: unless-stopped

  camtester-checker:
    image: camtester-checker
    container_name: camtester-checker
    build: ./camtester-checker
    environment:
      NATS_URL: "nats://camtester-nats:4222"
      NATS_CLUSTER_ID: "camtester"
      NATS_CLIENT_ID: "camtester-checker"
      RESTREAMER_PROVIDER_URI: "http://restreamer-provider"
      GEO_LOCATION: "moscow"
      CONCURRENCY: "100"
    depends_on:
      - camtester-nats
      - restreamer-provider
    restart: unless-stopped

  camtester-prober:
    image: camtester-prober
    container_name: camtester-prober
    build: ./camtester-prober
    environment:
      NATS_URL: "nats://camtester-nats:4222"
      NATS_CLUSTER_ID: "camtester"
      NATS_CLIENT_ID: "camtester-prober"
      RESTREAMER_PROVIDER_URI: "http://restreamer-provider"
      GEO_LOCATION: "moscow"
      CONCURRENCY: "100"
    depends_on:
      - camtester-nats
      - restreamer-provider
    restart: unless-stopped

  camtester-core:
    image: camtester-core
    container_name: camtester-core
    build: ./camtester-core
    environment:
      JWT_SECRET: "secret"
      REDIS_CLUSTER_ADDRS: "camtester-redis-cluster:7000,camtester-redis-cluster:7001,camtester-redis-cluster:7002"
      NATS_URL: "nats://camtester-nats:4222"
      NATS_CLUSTER_ID: "camtester"
      NATS_CLIENT_ID: "camtester-core"
      CONCURRENCY: "100"
    ports:
      - 127.0.0.1:80:80
    depends_on:
      - camtester-redis-cluster
      - camtester-nats
    restart: unless-stopped

volumes:
  restreamer-provider:
