// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package postgres

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	_ = packr.PackJSONBytes("./migrations", "1_init.up.sql", "\"Y3JlYXRlIHRhYmxlIHRhc2sgKAogICAgaWQgYmlnc2VyaWFsIHByaW1hcnkga2V5LAogICAgdHlwZSB0ZXh0IG5vdCBudWxsLAogICAgcGF5bG9hZCBqc29uYiBub3QgbnVsbAopOwoKY3JlYXRlIHRhYmxlIHRhc2tfcmVzdWx0ICgKICAgIGlkIGJpZ3NlcmlhbCBwcmltYXJ5IGtleSwKICAgIHRhc2tfaWQgYmlnaW50IG5vdCBudWxsIHJlZmVyZW5jZXMgdGFzayAoaWQpIHVuaXF1ZSwKICAgIG9rIGJvb2wgbm90IG51bGwsCiAgICBwYXlsb2FkIGpzb25iIG5vdCBudWxsCik7Cg==\"")
}
